export const START_GET_RELEASES = "START_GET_RELEASES";
export const GET_RELEASES_SUCCESS = "GET_RELEASES_SUCCESS";
export const GET_RELEASES_FAILURE = "GET_RELEASES_FAILURE";
export const SET_PARAMS = "SET_PARAMS";
